# time: O(1) space: O(N)
def likes(names):# time: O(1) space: O(N)
    if len(names) == 1:# time: O(1) space: O(1)
        return f'{names[0]} likes this'# time: O(1) space: O(1)
    elif len(names) < 1:# time: O(1) space: O(1)
        return 'no one likes this'# time: O(1) space: O(1)
    elif len(names) == 2:# time: O(1) space: O(1)
        return f'{names[0]} and {names[1]} like this'# time: O(1) space: O(1)
    elif len(names) == 3:# time: O(1) space: O(1)
        return f'{names[0]}, {names[1]} and {names[2]} like this'# time: O(1) space: O(1)
    else:# time: O(1) space: O(1)
        return f'{names[0]}, {names[1]} and {len(names)-2} others like this'# time: O(1) space: O(1)